incercareProiect/Models/Pescatarian.cs
using System;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace incercareProiect.Models
{
	public class Pescatarian
	{
        public int Id { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string? Name { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
        [Required]
        [StringLength(30)]
        public string? Type { get; set; }

        [Range(1, 100)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        public string? Rating { get; set; }
    }
}

incercareProiect/Controllers/PescatarianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using incercareProiect.Models;
using MvcMovie.Models;

namespace incercareProiect.Controllers
{
    public class PescatarianController : Controller
    {
        private readonly MvcPescatarianContext _context;

        public PescatarianController(MvcPescatarianContext context)
        {
            _context = context;
        }

        // GET: Pescatarian
        public async Task<IActionResult> Index(string dishType, string searchString)
        {
            if (_context.Pescatarian == null)
            {
                return Problem("Entity set 'MvcMovieContext.Pescatarian'  is null.");
            }

            // Use LINQ to get list of genres.
            IQueryable<string> typeQuery = from m in _context.Pescatarian
                                           orderby m.Type
                                           select m.Type;
            var pescatarian = from m in _context.Pescatarian
                           select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                pescatarian = pescatarian.Where(s => s.Name!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(dishType))
            {
                pescatarian = pescatarian.Where(x => x.Type == dishType);
            }

            var dishTypeVM = new PescatarianTypeViewModel
            {
                Types = new SelectList(await typeQuery.Distinct().ToListAsync()),
                Pescatarians = await pescatarian.ToListAsync()
            };

            return View(dishTypeVM);
        }

        // GET: Pescatarian/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pescatarian == null)
            {
                return NotFound();
            }

            var pescatarian = await _context.Pescatarian
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pescatarian == null)
            {
                return NotFound();
            }

            return View(pescatarian);
        }

        // GET: Pescatarian/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pescatarian/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Type,Price,Rating")] Pescatarian pescatarian, String PasswordString)
        {
            if (PasswordString != "admin")
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Add(pescatarian);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pescatarian);
        }

        // GET: Pescatarian/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pescatarian == null)
            {
                return NotFound();
            }

            var pescatarian = await _context.Pescatarian.FindAsync(id);
            if (pescatarian == null)
            {
                return NotFound();
            }
            return View(pescatarian);
        }

        // POST: Pescatarian/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Type,Price,Rating")] Pescatarian pescatarian, String PasswordString)
        {
            if (PasswordString != "admin")
            {
                return NotFound();
            }

            if (id != pescatarian.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pescatarian);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PescatarianExists(pescatarian.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pescatarian);
        }

        // GET: Pescatarian/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pescatarian == null)
            {
                return NotFound();
            }

            var pescatarian = await _context.Pescatarian
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pescatarian == null)
            {
                return NotFound();
            }

            return View(pescatarian);
        }

        // POST: Pescatarian/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pescatarian == null)
            {
                return Problem("Entity set 'MvcPescatarianContext.Pescatarian'  is null.");
            }
            var pescatarian = await _context.Pescatarian.FindAsync(id);
            if (pescatarian != null)
            {
                _context.Pescatarian.Remove(pescatarian);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PescatarianExists(int id)
        {
          return (_context.Pescatarian?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

incercareProiect/Views/Pescatarian/Create.cshtml
@model incercareProiect.Models.Pescatarian

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pescatarian</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div><br />
            <b>Administrator Password: </b><input type="password" name="PasswordString" /><br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

incercareProiect/Views/Pescatarian/Delete.cshtml
@model incercareProiect.Models.Pescatarian

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pescatarian</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
    @*<br /><b>Administrator Password: </b><input type="password" name="PasswordString" /><br />*@
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

incercareProiect/Views/Pescatarian/Details.cshtml
@model incercareProiect.Models.Pescatarian

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pescatarian</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

incercareProiect/Views/Pescatarian/Edit.cshtml
@model incercareProiect.Models.Pescatarian

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pescatarian</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div><br />
            <b>Administrator Password: </b><input type="password" name="PasswordString" /><br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

incercareProiect/Views/Pescatarian/Index.cshtml
@model MvcMovie.Models.PescatarianTypeViewModel

@{
    ViewData["Title"] = "Pescatarian Menu";
}

<h1>Pescatarian Menu</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Pescatarian" asp-action="Index">
    <p>
        <select asp-for="DishType" asp-items="Model.Types">
            <option value="">All</option>
        </select>

        Dish name: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pescatarians![0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pescatarians![0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pescatarians![0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pescatarians[0].Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Pescatarians!)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>